### PR TITLE
Use `prefer_literal` flag in `overload`

### LINKED ISSUE #115: AttributeError: 'Integer' object has no attribute 'literal_value'
```
File ~/mambaforge/envs/qe/lib/python3.10/site-packages/interpolation/splines/eval_splines.py:100, in __eval_spline(grid, C, points, out, k, diff, extrap_mode)
     98 @overload(_eval_spline)
     99 def __eval_spline(grid, C, points, out=None, k=1, diff="None", extrap_mode="linear"):
--> 100     kk = (k).literal_value
    101     diffs = (diff).literal_value
    102     extrap_ = (extrap_mode).literal_value

AttributeError: 'Integer' object has no attribute 'literal_value'
```

Found in: https://github.com/QuantEcon/lecture-python-advanced.myst/issues/163

### PR DESCRIPTION
**Pull request by kp992**
Fixes #115.

With this diff and `numba=0.60`, all the `splines` tests are working fine:
```bash
% pytest interpolation/splines/tests
============================= test session starts ==============================
platform darwin -- Python 3.10.12, pytest-8.1.0, pluggy-1.4.0
rootdir: /Users/kpl/repos/interpolation.py
configfile: pyproject.toml
plugins: anyio-4.0.0
collected 13 items                                                             

interpolation/splines/tests/test_cubic_splines.py ....                   [ 30%]
interpolation/splines/tests/test_derivatives.py .                        [ 38%]
interpolation/splines/tests/test_eval_splines.py .                       [ 46%]
interpolation/splines/tests/test_fortran_order.py ..                     [ 61%]
interpolation/splines/tests/test_hermite_splines.py .                    [ 69%]
interpolation/splines/tests/test_multilinear_extrap.py .                 [ 76%]
interpolation/splines/tests/test_object_api.py .                         [ 84%]
interpolation/splines/tests/test_readonly.py ..                          [100%]

============================= 13 passed in 23.71s ==============================

```

cc @albop

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @kp992. 

@albop this looks good to me. If you have time it would be great to merge and release an update.

**Comment by mmcky** [comment]
@kp992 will this only work for `numba>=0.60`? We will likely need to cater for a couple of versions of `numba`

**Comment by kp992** [comment]
@kp992 This works for numba=0.60, 0.59 and 0.58. I have tested them locally.

**Comment by albop** [comment]
Thank you very much @kp992  !
I wasn' t sure how to deal with this new numba behaviour when they removed generated_jit.
Your patch works and looks logical.
I'll merge it now. The tests in master still cover python 3.8, which is an older version of numba. Should be informative.

**Pull request merged**
