### PR TITLE
TEST: nonempty result

### PR DESCRIPTION
**Pull request by albop**
As proposed by @kp992, check that multilinear call returns non-None result

### CODE REVIEW

**Comment by mmcky** [comment]
@albop is this PR needed before release? I could use `main` branch version if release is held up.

**Comment by albop** [comment]
Well, so far this PR is only the test. Which doesn't pass on the main branch. 
I guess the solution is there though, in the other thread

**Comment by albop** [comment]
@mmcky : now main should be working, and nothing is holding the release. Save one little point:
there is a bug in numba that has been fixed only in the last release, which in certain cases affects interpolation routines (if you do repeated calls while alternating number of dimensions). Which would be a good reason to bump the numba version. Unless you have some version constraint of yours ?

**Comment by mmcky** [comment]
@albop we work to the version of `numba` that is distributed with the latest `anaconda` distribution as our baseline. however if you need `numba > 0.59` and it is pinned in your `setup.py` (or equivalent) then it will get upgraded automatically as our lectures build so that shouldn't be a problem for us.

**Pull request merged**
