### PR TITLE
FIX: compatibility with numba 0.47 and Anaconda.

### PR DESCRIPTION
**Pull request by albop**
I fixed the import issue with conda <0.49. For a different reason it doesn't work for conda<=0.46. Also the dependencies were adjusted so that the it shouldn't pull any package that is not in latest anaconda.

### CODE REVIEW

**Comment by mmcky** [comment]
Thanks @albop

**Comment by albop** [comment]
Should be good. I wrote a compatibility fix and updated both Pip and Conda versions. It is compatible with numba>=0.47 (tested) and it shouldn't pull any dependency beyond anaconda.

**Comment by albop** [comment]
@mmcky : can you test to see if it works for you ?

**Comment by mmcky** [comment]
thanks @albop -- the update has fixed the `navy_captain` lecture and we are working on the final `numba` issue which is unrelated to `interpolations` for `odu`. Thanks so much for the update. That is a big help.

**Comment by albop** [comment]
You're welcome. What's the numba issue ?

**Comment by mmcky** [comment]
It appears that there was an issue with using `lambda` functions. 

https://github.com/QuantEcon/lecture-python/pull/210

**Pull request merged**
